--
-- Name: bids; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bids (
    amount numeric(7,2) NOT NULL,
    deleted boolean NOT NULL,
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    "time" timestamp(6) without time zone NOT NULL,
    user_id bigint NOT NULL,
    version bigint,
    comment character varying(255)
);


--
-- Name: bids_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_lanes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_lanes (
    fuel_surcharge numeric(7,2),
    price numeric(7,2),
    valid_from date,
    valid_to date,
    weight double precision,
    customer_company_id bigint NOT NULL,
    from_location_id bigint NOT NULL,
    id bigint NOT NULL,
    linked_lane_id bigint,
    to_location_id bigint NOT NULL,
    lane_name character varying(255),
    route character varying(255),
    shipment_type character varying(255),
    temperature character varying(255),
    transport_type character varying(255),
    type character varying(255),
    CONSTRAINT company_lanes_shipment_type_check CHECK (((shipment_type)::text = ANY ((ARRAY['FTL'::character varying, 'LTL'::character varying])::text[]))),
    CONSTRAINT company_lanes_transport_type_check CHECK (((transport_type)::text = ANY ((ARRAY['TILT'::character varying, 'REF'::character varying, 'JUMBO'::character varying, 'MEGA'::character varying, 'BOX'::character varying, 'SMALL'::character varying, 'CONTAINER'::character varying])::text[]))),
    CONSTRAINT company_lanes_type_check CHECK (((type)::text = ANY ((ARRAY['ONE_WAY'::character varying, 'ROUND_TRIP'::character varying])::text[])))
);


--
-- Name: company_lanes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_lanes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_lanes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: lane_penalty; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lane_penalty (
    value numeric(7,2),
    customer_company_id bigint,
    id bigint NOT NULL,
    type character varying(255),
    unit character varying(255),
    CONSTRAINT lane_penalty_type_check CHECK (((type)::text = ANY ((ARRAY['CANCELED_BY_CLIENT'::character varying, 'CANCELED_BY_US'::character varying])::text[]))),
    CONSTRAINT lane_penalty_unit_check CHECK (((unit)::text = ANY ((ARRAY['EUR'::character varying, 'PERCENT'::character varying])::text[])))
);


--
-- Name: lane_penalty_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lane_penalty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lane_penalty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.location (
    country_code character varying(2) NOT NULL,
    id bigint NOT NULL,
    place_name character varying(255),
    zip_code character varying(255) NOT NULL
);


--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    department_id bigint,
    id bigint NOT NULL,
    priority character varying(255),
    role character varying(255),
    CONSTRAINT profiles_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT profiles_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT_SPECIALIST'::character varying, 'TRANSPORT_SPECIALIST'::character varying, 'SALES_SPECIALIST'::character varying, 'ASSISTANT'::character varying])::text[])))
);


--
-- Name: request_competitors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_competitors (
    request_id bigint NOT NULL,
    user_id bigint
);


--
-- Name: requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requests (
    archived boolean NOT NULL,
    bid_price numeric(7,2),
    client_price numeric(7,2),
    dangerous boolean NOT NULL,
    loading_meter double precision,
    profit_margin numeric(7,2),
    weight double precision,
    author_id bigint,
    customer_company_id bigint,
    dispatcher_id bigint,
    end_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    issue_date timestamp(6) without time zone NOT NULL,
    lane_id bigint,
    start_date timestamp(6) without time zone NOT NULL,
    version bigint,
    request_type character varying(31) NOT NULL,
    refuse_reason character varying(64),
    comments character varying(1000),
    customer_reference character varying(255),
    shipment_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    temperature character varying(255),
    tid character varying(255),
    transport_type character varying(255) NOT NULL,
    from_location_ids_order jsonb,
    to_location_ids_order jsonb,
    CONSTRAINT requests_shipment_type_check CHECK (((shipment_type)::text = ANY ((ARRAY['FTL'::character varying, 'LTL'::character varying])::text[]))),
    CONSTRAINT requests_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'BIDDING'::character varying, 'OFFERED'::character varying, 'ACCEPTED'::character varying, 'REFUSED'::character varying])::text[]))),
    CONSTRAINT requests_transport_type_check CHECK (((transport_type)::text = ANY ((ARRAY['TILT'::character varying, 'REF'::character varying, 'JUMBO'::character varying, 'MEGA'::character varying, 'BOX'::character varying, 'SMALL'::character varying, 'CONTAINER'::character varying])::text[])))
);


--
-- Name: requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: shipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment (
    planned_drop_date date NOT NULL,
    planned_load_date date NOT NULL,
    carrier_company_id bigint,
    dispatcher_id bigint,
    id bigint NOT NULL,
    version bigint,
    license_plate character varying(250),
    transport_order character varying(250),
    comments character varying(1000),
    cancel_reason character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT shipment_cancel_reason_check CHECK (((cancel_reason)::text = ANY ((ARRAY['CANCELLED_BY_CLIENT'::character varying, 'CANCELLED_BY_US'::character varying])::text[]))),
    CONSTRAINT shipment_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'LOADED'::character varying, 'DROPPED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: shipment_timestamp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment_timestamp (
    at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT shipment_timestamp_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'LOADED'::character varying, 'DROPPED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: shipment_timestamp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipment_timestamp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_timestamp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    version bigint,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    user_type character varying(255) NOT NULL,
    CONSTRAINT users_user_type_check CHECK (((user_type)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'EMPLOYEE'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bids bids_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT bids_pkey PRIMARY KEY (id);


--
-- Name: company_lanes company_lanes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT company_lanes_pkey PRIMARY KEY (id);


--
-- Name: company company_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_name_key UNIQUE (name);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: department department_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_code_key UNIQUE (code);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);

--
-- Name: lane_penalty lane_penalty_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lane_penalty
    ADD CONSTRAINT lane_penalty_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);

--
-- Name: shipment shipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT shipment_pkey PRIMARY KEY (id);


--
-- Name: shipment_timestamp shipment_timestamp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_timestamp
    ADD CONSTRAINT shipment_timestamp_pkey PRIMARY KEY (id);


--
-- Name: location uq_country_zip_place; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT uq_country_zip_place UNIQUE (country_code, zip_code, place_name);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

--
-- Name: company_lanes fk1f80cc65d1g5wkcfmi7i9ey5x; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fk1f80cc65d1g5wkcfmi7i9ey5x FOREIGN KEY (from_location_id) REFERENCES public.location(id);


--
-- Name: company_lanes fk43qo7nboko6hwyknxtm2gmbsa; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fk43qo7nboko6hwyknxtm2gmbsa FOREIGN KEY (customer_company_id) REFERENCES public.company(id);


--
-- Name: profiles fk55e5d3sfwkob62wtprm633alk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk55e5d3sfwkob62wtprm633alk FOREIGN KEY (id) REFERENCES public.users(id);


--
-- Name: shipment fk6rcm95yauuqeg06qyxcdx7qqw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fk6rcm95yauuqeg06qyxcdx7qqw FOREIGN KEY (carrier_company_id) REFERENCES public.company(id);


--
-- Name: lane_penalty fk8xqge2k7wptanixsd2hm09dig; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lane_penalty
    ADD CONSTRAINT fk8xqge2k7wptanixsd2hm09dig FOREIGN KEY (customer_company_id) REFERENCES public.company(id);


--
-- Name: requests fkacj49r0m4w7oaebkkqwkgqdk4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT fkacj49r0m4w7oaebkkqwkgqdk4 FOREIGN KEY (customer_company_id) REFERENCES public.company(id);


--
-- Name: shipment fkfs6tsga7xks7iftfvxgmfvaue; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fkfs6tsga7xks7iftfvxgmfvaue FOREIGN KEY (id) REFERENCES public.requests(id);


--
-- Name: profiles fkishahtpx87jsfgbfpq3tir4q1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fkishahtpx87jsfgbfpq3tir4q1 FOREIGN KEY (department_id) REFERENCES public.department(id);


--
-- Name: request_competitors fkjb9woerx5fdj1ppyyitkurvgg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.request_competitors
    ADD CONSTRAINT fkjb9woerx5fdj1ppyyitkurvgg FOREIGN KEY (request_id) REFERENCES public.requests(id);


--
-- Name: shipment_timestamp fkjocf1agwg6jdnn0op941uscbm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_timestamp
    ADD CONSTRAINT fkjocf1agwg6jdnn0op941uscbm FOREIGN KEY (shipment_id) REFERENCES public.shipment(id);


--
-- Name: requests fklhe5m8o9b2pd2l9qgq64on8us; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT fklhe5m8o9b2pd2l9qgq64on8us FOREIGN KEY (lane_id) REFERENCES public.company_lanes(id);


--
-- Name: company_lanes fklq57cjtok53f9q8xce1x2orol; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fklq57cjtok53f9q8xce1x2orol FOREIGN KEY (linked_lane_id) REFERENCES public.company_lanes(id);


--
-- Name: bids fkmb21nl8gr3srgnlch3s18oqv9; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fkmb21nl8gr3srgnlch3s18oqv9 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: company_lanes fknj89n8xow4jb8nmell52tj9k2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fknj89n8xow4jb8nmell52tj9k2 FOREIGN KEY (to_location_id) REFERENCES public.location(id);


--
-- Name: bids fkriu5ppr8untk4mq0942sg15qe; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fkriu5ppr8untk4mq0942sg15qe FOREIGN KEY (request_id) REFERENCES public.requests(id);