--type msi
--name iETMS
--vendor Maxim_Yakovitski

--dest target/installer
--input target/jpackage-input/app
--main-jar iet-desktop-1.0-SNAPSHOT.jar
--main-class com.mayak.iet.app.DesktopLauncher

--java-options -Dspring.profiles.active=prod
--java-options -Dfile.encoding=UTF-8
--java-options -Duser.language=en
--java-options -Duser.country=US

--java-options -Djpackage.app-version=${app.version}
--java-options -Dapp.name=iETMS

--win-menu
--win-shortcut
--win-dir-chooser
--install-dir iETMS
--win-upgrade-uuid 548FEBED-D910-4079-9911-7AB6B0B66BE8
--win-post-install target/installer/register-native-host.bat

--icon target/classes/installer/ietms.ico
--verbose