--type msi
--name iETMS
--vendor iETMS
--app-version 1.0.0
--win-upgrade-uuid 548FEBED-D910-4079-9911-7AB6B0B66BE8
--win-menu
--win-shortcut
--win-dir-chooser
--install-dir iETMS
--icon src/main/resources/installer/ietms.ico