--
-- Name: bids; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bids (
    amount numeric(7,2) NOT NULL,
    deleted boolean NOT NULL,
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    "time" timestamptz NOT NULL,
    user_id bigint NOT NULL,
    version bigint,
    comment text
);


--
-- Name: bids_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);


--
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: company_lanes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.company_lanes (
    fuel_surcharge numeric(7,2),
    price numeric(7,2),
    valid_from date,
    valid_to date,
    weight double precision,
    customer_company_id bigint NOT NULL,
    from_location_id bigint NOT NULL,
    id bigint NOT NULL,
    linked_lane_id bigint,
    to_location_id bigint NOT NULL,
    lane_name character varying(255),
    route character varying(255),
    shipment_type character varying(255),
    temperature character varying(255),
    transport_type character varying(255),
    type character varying(255),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT company_lanes_shipment_type_check CHECK (((shipment_type)::text = ANY ((ARRAY['FTL'::character varying, 'LTL'::character varying])::text[]))),
    CONSTRAINT company_lanes_transport_type_check CHECK (((transport_type)::text = ANY ((ARRAY['TILT'::character varying, 'REF'::character varying, 'JUMBO'::character varying, 'MEGA'::character varying, 'BOX'::character varying, 'SMALL'::character varying, 'CONTAINER'::character varying])::text[]))),
    CONSTRAINT company_lanes_type_check CHECK (((type)::text = ANY ((ARRAY['ONE_WAY'::character varying, 'ROUND_TRIP'::character varying])::text[])))
);


--
-- Name: company_lanes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.company_lanes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_lanes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: department; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.department (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: lane_penalty; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lane_penalty (
    value numeric(7,2),
    customer_company_id bigint,
    id bigint NOT NULL,
    type character varying(255),
    unit character varying(255),
    CONSTRAINT lane_penalty_type_check CHECK (((type)::text = ANY ((ARRAY['CANCELED_BY_CLIENT'::character varying, 'CANCELED_BY_US'::character varying])::text[]))),
    CONSTRAINT lane_penalty_unit_check CHECK (((unit)::text = ANY ((ARRAY['EUR'::character varying, 'PERCENT'::character varying])::text[])))
);


--
-- Name: lane_penalty_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lane_penalty ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lane_penalty_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.location (
    country_code character varying(2) NOT NULL,
    id bigint NOT NULL,
    place_name character varying(255),
    zip_code character varying(255) NOT NULL
);


--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.profiles (
    department_id bigint,
    id bigint NOT NULL,
    priority character varying(255),
    role character varying(255),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT profiles_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT profiles_role_check CHECK (((role)::text = ANY ((ARRAY['CLIENT_SPECIALIST'::character varying, 'TRANSPORT_SPECIALIST'::character varying, 'SALES_SPECIALIST'::character varying, 'ASSISTANT'::character varying])::text[])))
);


--
-- Name: request_competitors; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.request_competitors (
    request_id bigint NOT NULL,
    user_id bigint NOT NULL,
    PRIMARY KEY (request_id, user_id)
);


--
-- Name: requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.requests (
    archived boolean NOT NULL,
    bid_price numeric(7,2),
    client_price numeric(7,2),
    dangerous boolean NOT NULL,
    loading_meter double precision,
    profit_margin numeric(7,2),
    weight double precision,
    author_id bigint,
    customer_company_id bigint,
    dispatcher_id bigint,
    end_date timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    issue_date timestamptz NOT NULL,
    lane_id bigint,
    start_date timestamp(6) without time zone NOT NULL,
    version bigint,
    request_type character varying(31) NOT NULL,
    refuse_reason character varying(64),
    comments text,
    customer_reference character varying(255),
    shipment_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    temperature character varying(255),
    tid character varying(255),
    transport_type character varying(255) NOT NULL,
    from_location_ids_order jsonb,
    to_location_ids_order jsonb,
    CONSTRAINT requests_shipment_type_check CHECK (((shipment_type)::text = ANY ((ARRAY['FTL'::character varying, 'LTL'::character varying])::text[]))),
    CONSTRAINT requests_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'IN_PROGRESS'::character varying, 'BIDDING'::character varying, 'OFFERED'::character varying, 'ACCEPTED'::character varying, 'REFUSED'::character varying])::text[]))),
    CONSTRAINT requests_transport_type_check CHECK (((transport_type)::text = ANY ((ARRAY['TILT'::character varying, 'REF'::character varying, 'JUMBO'::character varying, 'MEGA'::character varying, 'BOX'::character varying, 'SMALL'::character varying, 'CONTAINER'::character varying])::text[])))
);


--
-- Name: requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: shipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment (
    planned_drop_date date NOT NULL,
    planned_load_date date NOT NULL,
    carrier_company_id bigint,
    dispatcher_id bigint,
    id bigint NOT NULL,
    version bigint,
    license_plate character varying(250),
    transport_order character varying(250),
    comments text,
    cancel_reason character varying(255),
    status character varying(255) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT shipment_cancel_reason_check CHECK (((cancel_reason)::text = ANY ((ARRAY['CANCELLED_BY_CLIENT'::character varying, 'CANCELLED_BY_US'::character varying])::text[]))),
    CONSTRAINT shipment_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'LOADED'::character varying, 'DROPPED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: shipment_timestamp; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.shipment_timestamp (
    at timestamptz NOT NULL,
    id bigint NOT NULL,
    shipment_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT shipment_timestamp_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'LOADED'::character varying, 'DROPPED'::character varying, 'CANCELED'::character varying])::text[])))
);


--
-- Name: shipment_timestamp_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.shipment_timestamp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shipment_timestamp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    version bigint,
    token_version integer NOT NULL DEFAULT 0,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    surname character varying(255) NOT NULL,
    user_type character varying(255) NOT NULL,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT users_user_type_check CHECK (((user_type)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'EMPLOYEE'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: bids bids_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bids
    ADD CONSTRAINT bids_pkey PRIMARY KEY (id);


--
-- Name: company_lanes company_lanes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT company_lanes_pkey PRIMARY KEY (id);


--
-- Name: company company_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_name_key UNIQUE (name);


--
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- Name: department department_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_code_key UNIQUE (code);


--
-- Name: department department_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.department
    ADD CONSTRAINT department_pkey PRIMARY KEY (id);

--
-- Name: lane_penalty lane_penalty_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lane_penalty
    ADD CONSTRAINT lane_penalty_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: profiles profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);


--
-- Name: requests requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.requests
    ADD CONSTRAINT requests_pkey PRIMARY KEY (id);

--
-- Name: shipment shipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT shipment_pkey PRIMARY KEY (id);


--
-- Name: shipment_timestamp shipment_timestamp_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.shipment_timestamp
    ADD CONSTRAINT shipment_timestamp_pkey PRIMARY KEY (id);


--
-- Name: location uq_country_zip_place; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT uq_country_zip_place UNIQUE (country_code, zip_code, place_name);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

-- =============================================================================
-- FOREIGN KEY CONSTRAINTS
-- =============================================================================

-- company_lanes → location (from)
ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fk_company_lanes_from_location
        FOREIGN KEY (from_location_id) REFERENCES public.location(id);

-- company_lanes → location (to)
ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fk_company_lanes_to_location
        FOREIGN KEY (to_location_id) REFERENCES public.location(id);

-- company_lanes → company
ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fk_company_lanes_company
        FOREIGN KEY (customer_company_id) REFERENCES public.company(id);

-- company_lanes → company_lanes (self-reference для linked lane)
ALTER TABLE ONLY public.company_lanes
    ADD CONSTRAINT fk_company_lanes_linked_lane
        FOREIGN KEY (linked_lane_id) REFERENCES public.company_lanes(id);

-- profiles → users (1-to-1)
ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk_profiles_user
        FOREIGN KEY (id) REFERENCES public.users(id);

-- profiles → department
ALTER TABLE ONLY public.profiles
    ADD CONSTRAINT fk_profiles_department
        FOREIGN KEY (department_id) REFERENCES public.department(id);

-- lane_penalty → company
ALTER TABLE ONLY public.lane_penalty
    ADD CONSTRAINT fk_lane_penalty_company
        FOREIGN KEY (customer_company_id) REFERENCES public.company(id);

-- requests → company
ALTER TABLE ONLY public.requests
    ADD CONSTRAINT fk_requests_company
        FOREIGN KEY (customer_company_id) REFERENCES public.company(id);

-- requests → company_lanes
ALTER TABLE ONLY public.requests
    ADD CONSTRAINT fk_requests_lane
        FOREIGN KEY (lane_id) REFERENCES public.company_lanes(id);

-- request_competitors → requests
ALTER TABLE ONLY public.request_competitors
    ADD CONSTRAINT fk_request_competitors_request
        FOREIGN KEY (request_id) REFERENCES public.requests(id);

-- shipment → requests (1-to-1)
ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fk_shipment_request
        FOREIGN KEY (id) REFERENCES public.requests(id);

-- shipment → company (carrier)
ALTER TABLE ONLY public.shipment
    ADD CONSTRAINT fk_shipment_carrier_company
        FOREIGN KEY (carrier_company_id) REFERENCES public.company(id);

-- shipment_timestamp → shipment
ALTER TABLE ONLY public.shipment_timestamp
    ADD CONSTRAINT fk_shipment_timestamp_shipment
        FOREIGN KEY (shipment_id) REFERENCES public.shipment(id);

-- bids → users
ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fk_bids_user
        FOREIGN KEY (user_id) REFERENCES public.users(id);

-- bids → requests
ALTER TABLE ONLY public.bids
    ADD CONSTRAINT fk_bids_request
        FOREIGN KEY (request_id) REFERENCES public.requests(id);

-- ===== INDEXES =====

-- -----------------------------------------------------------------------------
-- TABLE: requests
-- Queries: filterByQuery, findAllActiveSorted, findExpiredRequests,
--          findRequestsForArchiving, countBy*, findFullBy*
-- -----------------------------------------------------------------------------

-- Most common filter: archived=false (used in almost every query)
CREATE INDEX idx_requests_archived
    ON public.requests (archived);

-- Status filtering + ordering (filterByQuery, findExpiredRequests)
CREATE INDEX idx_requests_status
    ON public.requests (status);

-- Composite: the most frequent combo (archived + status)
CREATE INDEX idx_requests_archived_status
    ON public.requests (archived, status);

-- Author-based queries (countByAuthorId, findMyShipmentsForDate via join, existsByAuthorId)
CREATE INDEX idx_requests_author_id
    ON public.requests (author_id);

-- Dispatcher-based queries (countByDispatchedUser, existsByDispatcherId)
CREATE INDEX idx_requests_dispatcher_id
    ON public.requests (dispatcher_id);

-- Customer company filtering (filterByQuery, existsByCustomer_Id)
CREATE INDEX idx_requests_customer_company_id
    ON public.requests (customer_company_id);

-- Date-based queries (findExpiredRequests, findRequestsForArchiving, countBy*, analytics)
CREATE INDEX idx_requests_issue_date
    ON public.requests (issue_date);

-- Lane filtering (existsByLaneId used in LaneService)
CREATE INDEX idx_requests_lane_id
    ON public.requests (lane_id);

-- Request type discrimination (JPA inheritance + findAllByType)
CREATE INDEX idx_requests_request_type
    ON public.requests (request_type);

-- Composite for scheduler: archived=false + status IN (...) + issue_date < threshold
CREATE INDEX idx_requests_archived_status_issue_date
    ON public.requests (archived, status, issue_date);

-- -----------------------------------------------------------------------------
-- TABLE: bids
-- Queries: findByRequest, findByRequestAndDeletedFalse,
--          findByRequestOrderByTimeDesc, findByUserAndTimeBetween, userStats
-- -----------------------------------------------------------------------------

-- Most common: filter by request_id
CREATE INDEX idx_bids_request_id
    ON public.bids (request_id);

-- Composite: request + not deleted (findByRequestAndDeletedFalse — used in getBestBid)
CREATE INDEX idx_bids_request_id_deleted
    ON public.bids (request_id, deleted);

-- User + time range (findByUserAndTimeBetween, userStats CTE)
CREATE INDEX idx_bids_user_id_time
    ON public.bids (user_id, time);

-- -----------------------------------------------------------------------------
-- TABLE: shipment
-- Queries: findMyShipmentsForDate (via request.authorId join),
--          findMyTransportShipments (dispatcher_id), existsByRequestId
-- -----------------------------------------------------------------------------

-- Dispatcher-based queries (findMyTransportShipments)
CREATE INDEX idx_shipment_dispatcher_id
    ON public.shipment (dispatcher_id);

-- Carrier company (ShipmentService.applyCarrier)
CREATE INDEX idx_shipment_carrier_company_id
    ON public.shipment (carrier_company_id);

-- Status (cancel checks, status transitions)
CREATE INDEX idx_shipment_status
    ON public.shipment (status);

-- -----------------------------------------------------------------------------
-- TABLE: shipment_timestamp
-- Queries: loaded via @EntityGraph from ShipmentRepository
-- -----------------------------------------------------------------------------

CREATE INDEX idx_shipment_timestamp_shipment_id
    ON public.shipment_timestamp (shipment_id);

-- -----------------------------------------------------------------------------
-- TABLE: request_competitors
-- Queries: MEMBER OF r.competitorsId, userStats LEFT JOIN
-- -----------------------------------------------------------------------------

-- Index for reverse lookup (find requests by user)
CREATE INDEX idx_request_competitors_user_id
    ON public.request_competitors (user_id);

-- -----------------------------------------------------------------------------
-- TABLE: profiles
-- Queries: countByTypeAndDepartment, userStats (department filtering)
-- -----------------------------------------------------------------------------

CREATE INDEX idx_profiles_department_id
    ON public.profiles (department_id);

-- -----------------------------------------------------------------------------
-- TABLE: company_lanes
-- Queries: LaneRepository lookups, existsByLane
-- -----------------------------------------------------------------------------

CREATE INDEX idx_company_lanes_customer_company_id
    ON public.company_lanes (customer_company_id);

CREATE INDEX idx_company_lanes_from_location_id
    ON public.company_lanes (from_location_id);

CREATE INDEX idx_company_lanes_to_location_id
    ON public.company_lanes (to_location_id);

-- -----------------------------------------------------------------------------
-- TABLE: lane_penalty
-- Queries: loaded via company entity
-- -----------------------------------------------------------------------------

CREATE INDEX idx_lane_penalty_customer_company_id
    ON public.lane_penalty (customer_company_id);

-- -----------------------------------------------------------------------------
-- TABLE: users
-- Queries: DatabaseUserDetailsService (findByEmail), UserRepository
-- -----------------------------------------------------------------------------

-- email is already UNIQUE (implicit index), but make sure for login performance
-- (already exists as users_email_key — no action needed)

-- user_type for admin checks
CREATE INDEX idx_users_user_type
    ON public.users (user_type);