--type msi
--name iETMS
--vendor Maxim_Yakovitski

--dest target/installer
--input target/jpackage-input/app
--main-jar ietms-desktop-1.0-SNAPSHOT.jar
--main-class com.mayak.ietms.app.DesktopLauncher

--java-options -Dspring.profiles.active=prod
--java-options -Dfile.encoding=UTF-8
--java-options -Duser.language=en
--java-options -Duser.country=US
--java-options -Xms128m
--java-options -Xmx512m
--java-options -Dsun.zip.disableMemoryMapping=true
--java-options -XX:TieredStopAtLevel=1

--win-menu
--win-shortcut
--win-dir-chooser
--install-dir iETMS
--win-upgrade-uuid 548FEBED-D910-4079-9911-7AB6B0B66BE8

--icon target/classes/installer/ietms.ico
--verbose