spring:
  application:
    name: ietms-backend

management:
  metrics:
    tags:
      application: ${spring.application.name}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 36000000

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false