spring:
  application:
    name: ietms-backend

management:
  metrics:
    tags:
      application: ${spring.application.name}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 300000
    refresh-expiration-ms: 86400000